### ISSUE TITLE
Save/Update errors

### ISSUE THREAD

**Issue by kyleknighted** [jedfoster/SassMeister#103]
If I save a new gist I get the URL `http://sassmeister.com/gist/4acb4722913af2958ff8`

Which, if you try to go to that URL, it will give you an ISE 500 error.
The gist saves to `https://gist.github.com/anonymous/4acb4722913af2958ff8` instead of to my github account which it claims I'm signed in to.

Same glitch when I update a saved gist. The way I am currently getting around this is going to github, forking the gist, and then grabbing the new URL it creates and plugging it into sassmeister which picks it right up.

OSX 10.9.3
Chrome 35.0.1916.153

**Comment by jedfoster** [comment]
I believe this has been resolved.

**Comment by alfonsojon** [comment]
I'm having this issue, or one closely related to it..
