### ISSUE TITLE
⌘+S to save changes to gist

### ISSUE THREAD

**Issue by ezekg** [jedfoster/SassMeister#111]
Similar to how [MeteorPad](http://meteorpad.com/) does it. I do it by muscle memory, and always seem to wish it would save/update my gist instead of attempting to save the file.

**Comment by jedfoster** [comment]
This feature will ship with the v4 rewrite. No ETA on when that go live, but soon.

**Comment by ezekg** [comment]
Awesome to hear. 👌

**Comment by lukewatts** [comment]
Nice!
