### ISSUE TITLE
Allow configuration to output @warn @debug

### ISSUE THREAD

**Issue by KatieK2** [jedfoster/SassMeister#123]
Sassmeister doesn't output @warn and @debug directives. Ex:

http://sassmeister.com/gist/c7c72e2c5f53ab4d4059

It would be nice if there were a configuration option to show this debug information.

**Comment by mangelozzi** [comment]
To anyone trying to see the values of maps etc in Sass meister, I eventually figured out `meta.inspect`:
```sass
@use "sass:meta"

$palette : ("fg": (#202124, #ffffff))

.foo
    showme: meta.inspect($palette)
```
generates
```sass
.foo {
  showme: ("fg": (#202124, #ffffff))
}
```
