### ISSUE TITLE
New extension: Sassy Math

### ISSUE THREAD

**Issue by scottkellum** [jedfoster/SassMeister#130]
[Sassy Math](https://github.com/at-import/Sassy-math) does not seem to be available or updated in Sassmeister right now.

Due to the way Sassy-math works, the functions will likely be available to all Ruby Sass users even if they do not ask to have it imported just like special Compass math functions.

cc @snugug

**Comment by jedfoster** [comment]
Finally got around to fixing this for the 3.4 compiler. Not sure I want to go to the trouble of fixing it for 3.3 and 3.2, though.
