### ISSUE TITLE
Enable Breakpoint, Singularity, Toolkit for Libsass

### ISSUE THREAD

**Issue by Snugug** [jedfoster/SassMeister#136]
3.0.2 introduces maps and should mean that they won't blow up now. Might not be 100% compatible, but won't blow up. People are starting to file issues against them, so would like them to be able to show me.

All installable through Bower

**Comment by jedfoster** [comment]
I added the wrong Breakpoint in December (someone else apparently has a Sass library with the name `breakpoint` on Bower). That has been fixed.

The issues with Singularity and Toolkit have also been resolved.

All three libs will go out with the next release sometime this weekend.
