### ISSUE TITLE
libsass 3.1.0 has been released

### ISSUE THREAD

**Issue by drewwells** [jedfoster/SassMeister#137]
https://github.com/sass/libsass/releases/tag/3.1.0

**Comment by jedfoster** [comment]
But [node-sass](https://github.com/sass/node-sass/releases) has not been update yet. We are dependent on that project. As soon as that gets updated I'll the update the app.

**Comment by drewwells** [comment]
Should this be closed, or just reference the blocking commit? https://github.com/sass/node-sass/issues/602
