### ISSUE TITLE
Wrong Version of Lib

### ISSUE THREAD

**Issue by Undistraction** [jedfoster/SassMeister#138]
Sassmeister currently lists Position v0.2.14, but the version that is being added is much older. 

If you look at the [src](https://github.com/Undistraction/position/blob/master/dist/_position.scss) for v0.2.14 you can see the comments use `///`, but the version you are actually importing uses `/* */` comments which are preserved in the compiled output.

The last version to use `/* */` comments was v0.2.10.

**Comment by jedfoster** [comment]
The installed version is 0.2.14

**Comment by Undistraction** [comment]
Thanks for the fix.
