### ISSUE TITLE
New extension: include-media

### ISSUE THREAD

**Issue by eduardoboucas** [jedfoster/SassMeister#141]
A library for managing and writing media queries in Sass.

Useful links:
- [Website](http://include-media.com)
- [GitHub repo](https://github.com/eduardoboucas/include-media)
- [Article on CSS-Tricks](http://css-tricks.com/approaches-media-queries-sass/)
- [Article on David Walsh's blog](http://davidwalsh.name/sass-media-query)

**Comment by jedfoster** [comment]
Added to LibSass and 3.4 compilers. Will go out with the next release later this weekend.

**Comment by eduardoboucas** [comment]
@jedfoster did this go out?

**Comment by jedfoster** [comment]
It did, but wasn't visible because caching is a hard problem. Fixed now. Thanks!

**Comment by eduardoboucas** [comment]
When I click on "include-media" on the extensions list, it adds the `@import` fine when I'm using LibSass, but not on 3.4.

**Comment by eduardoboucas** [comment]
I think the `<li>` is missing the data attribute:

``` html
<!-- LibSass -->
<a data-import="include-media">include-media</a>
```

``` html
<!-- 3.4.11 -->
<a data-import="null">Include Media</a>
```

**Comment by eduardoboucas** [comment]
@jedfoster Don't know if you receive notifications from closed issues, so might as well mention you. :)

**Comment by jedfoster** [comment]
Fixed (for reals) now.
