### ISSUE TITLE
Errors are not displayed anymore using LibSass

### ISSUE THREAD

**Issue by HugoGiraudel** [jedfoster/SassMeister#144]
Since LibSass 3.1, errors are not displayed anymore in the CSS output when using LibSass.

Test:

```sass
@error "Test";
```

**Comment by HugoGiraudel** [comment]
Any progress on this? Until this is fixed, [Sass Compatibility](http://sass-compatibility.github.io/) is dead. :(

**Comment by jedfoster** [comment]
It's a node-sass issue. https://github.com/sass/node-sass/issues/646

I have no access to `@error` or `@debug`. The best I can do is return parse error messages.

**Comment by HugoGiraudel** [comment]
I'm confused. The linked issue does not mention `@error` at all. Plus, `@error` did show in the output not so long ago. How comes it doesn't work anymore?

**Comment by jedfoster** [comment]
Libsass doesn't handle logging (of errors, warnings, or debuggers—it's all the same) the way Ruby Sass does. I don't really understand how libsass and node-sass deal with logging under the hood, but all the output from `@debug`, `@warn`, and `@error` is sent to STDOUT or STDERR with no way to access it programmatically.

The node-sass APIs are frustratingly unstable; I have to make tweaks to the app or the tests _every_ time I update it, even with patches. But it's all there is and I don't write C, so there we are.
