### ISSUE TITLE
New extension: Sassdash

### ISSUE THREAD

**Issue by davidkpiano** [jedfoster/SassMeister#146]
https://github.com/davidkpiano/sassdash

**Comment by HugoGiraudel** [comment]
That would be nice. :)

**Comment by jedfoster** [comment]
Added for both Ruby Sass 3.4.12 and Libsass, but my tests fail on Libsass. I opened an issue on Sassdash, https://github.com/davidkpiano/sassdash/issues/14

Let me know when that issue has been resolved and I'll update.

**Comment by davidkpiano** [comment]
Hey @jedfoster, the issue has been resolved and Sassdash now fully supports Libsass.
