### ISSUE TITLE
New extension: Lost Grid

### ISSUE THREAD

**Issue by corysimmons** [jedfoster/SassMeister#147]
Thanks for including my other grid, Jeet. Lost is essentially the next evolution of Jeet and I'd love it if you'd include it on SassMeister. It's heavily maintained and clean with tons of additional features.

https://github.com/corysimmons/lost

Thank you!

**Comment by jedfoster** [comment]
@corysimmons Looks like you removed Sass support from this project; not sure it makes sense for SassMeister anymore.

**Comment by corysimmons** [comment]
Yeah sorry. Ported to PostCSS. It works with any preproccesor now but
probably doesn't make sense for sassmeister.
