### ISSUE TITLE
New extension: Sass MQ

### ISSUE THREAD

**Issue by kaelig** [jedfoster/SassMeister#149]
`mq()` is a responsive helper that helps you compose media queries in an elegant way. 

Repo: https://github.com/sass-mq/sass-mq
SassDoc: http://sass-mq.github.io/sass-mq/

Sass file:
https://github.com/sass-mq/sass-mq/blob/master/_mq.scss

Compatibility:
- Ruby Sass 3.3+
- Libsass 3.1+

I'm using it all the time, so it'd be super helpful to have it as an extension.
Let me know if I can do anything to help its integration.

**Comment by jedfoster** [comment]
Added. Will go out with the next release this afternoon.

**Comment by kaelig** [comment]
Thank you very much, I appreciate it.

**Comment by kaelig** [comment]
Hey @jedfoster, sass-mq was updated to v4, is this something you could update?
