### ISSUE TITLE
Could you add my extension?

### ISSUE THREAD

**Issue by ganlanyuan** [jedfoster/SassMeister#152]
Hi,
SassMeister is very cool and helpful, could you add my extension [Rocket](https://github.com/ganlanyuan/rocket) too?
Or is there any way I can use it on SassMeister?

Thanks a lot!
William Lin

**Comment by jedfoster** [comment]
Added. Will go out with the next release this afternoon.

**Comment by ganlanyuan** [comment]
Awesome!!!
Thanks ^^
