### ISSUE TITLE
New extension: Sassy-validation

### ISSUE THREAD

**Issue by Skoks** [jedfoster/SassMeister#153]
@jedfoster Hello Jed,

Can you please add [Sassy-validation](https://github.com/SassySuit/sassy-validation) ?

[Documentation](http://sassysuit.github.io/sassy-validation/)

Has to be compatible with: 
* Ruby Sass v3.2+
* LibSass v3.1+

Thank you

**Comment by jedfoster** [comment]
Added. Will go out with the next release this afternoon.

Added for LibSass, 3.4, and 3.3. I'm not making any updates to the 3.2 compiler anymore.

**Comment by Skoks** [comment]
@jedfoster Thank you
