### ISSUE TITLE
New Extension: Vary

### ISSUE THREAD

**Issue by Undistraction** [jedfoster/SassMeister#154]
Please add Vary; a very nicely put together lib for theming by @jaicab

Github: https://github.com/jaicab/sass-vary
Site: http://jaicab.com/sass-vary/

**Comment by jaicab** [comment]
Thanks for setting up this issue @Undistraction, it's a good time to ask for this since version 1.1 covers pretty much every scenario and won't change much from now. I'll update the demos removing vary's code as soon as it gets added. Thanks!

**Comment by jedfoster** [comment]
Added. Will go out with the next release this afternoon.
