### ISSUE TITLE
Update Neat to ~1.7.2 on Sass 3.4 compiler

### ISSUE THREAD

**Issue by jamierytlewski** [jedfoster/SassMeister#158]
When I try to use bourbon with Sass 3.4.14 none of the functions work properly, but they work great and fast with LibSass. I don't mind using LibSass, it's just not a 1 to 1 of what we are currently using.

http://www.screencast.com/t/dsPeLmC3jIu - LibSass (working)

http://www.screencast.com/t/8t1oM3Loz - Sass (not working).

Great product by the way! Absolutely love it.

**Comment by jedfoster** [comment]
Looks like this is actually an issue with the version of Neat installed for the 3.4 compiler. 3.4 has Neat v1.6.0 while LibSass has Neat v1.7.2.

Updating the version installed for 3.4 should fix this issue.

**Comment by jedfoster** [comment]
Looks like this got fixed somewhere along the way.
