### ISSUE TITLE
Ability to view/copy raw input

### ISSUE THREAD

**Issue by saper** [jedfoster/SassMeister#164]
I am having serious trouble getting my browser (running under X11) to get the copy+paste out of Sassmeister correctly. (In short: using CLIPBOARD selection works with Ctrl+C, but asserting primary selection just by a mouse selection doesn't).

While this is probably an issue how the browser and X Window System interact, would that be possible to have links to raw input content as well? (output is a bonus).

Just plain text, no styles, no javascript, preferably a predictable, stable URL.

**Comment by jedfoster** [comment]
Save a GitHub Gist from the "Cloud" menu, that will give you link to the Gist, which will contain both the input and the output.

**Comment by saper** [comment]
Seems like my custom content blocker was breaking links to "sandbox.sassmeister.com" and I was getting 403 from there and the GitHub options were not available at in the menu (I've only got the "Reset" option). Got the filter adjusted, but I still wonder if that needs to be so compilicated :)

Thanks!
