### ISSUE TITLE
Update Gist saving to null

### ISSUE THREAD

**Issue by lukewatts** [jedfoster/SassMeister#166]
Sometimes when I've been working on a "Sassmesiter-ization" ...when I log in to git hub and Saveas Gist everything works fine. However, sometimes even though I'm still logged in when I "Update Gist" it will update to a Github account called "Null" created in November 2013.

It's happened about 6 times now but I'm still unsure what causes it. It's not really consistent. I think it may be when I close the browser and repoen it, I'll still be logged in with Github and the work in Sassmeister is still there...but the link between the two has broken.

Anyone else experienced this?

**Comment by lukewatts** [comment]
Here's the page it tries to update to https://github.com/null

**Comment by jedfoster** [comment]
Is your browser clearing cookies when you close a window? Because that would cause this behavior.

**Comment by lukewatts** [comment]
I'm not sure to be perfectly honest. It's not something I've set my browser to do on purpose though, I do a lot of Php stuff so I need my cookie behaviour to be fairly in line with the norm. I'll keep an eye out for it happening again and I'll see if it's a cookie issue. I think we should leave this open for now until we've figured it out. What do you think?

Thanks.

**Comment by lukewatts** [comment]
I think cracked it! I often switch from the Sass syntax to SCSS and back again (I prefer writing in .sass but I need to convert it to .scss to copy and paste it into a book I'm working on).

It seems after converting from one or the other Sassmeister doesn't recognise the Gist anymore, or vice versa.

Does that make sense?

Hopefully that gives a clue to what might be happening.

**Comment by jedfoster** [comment]
That is definitely a useful data point. I've seen some odd behavior myself around syntax conversions. I'll take a look at this next week. Thanks!

**Comment by jedfoster** [comment]
@lukewatts I'm curious if this will still be an issue with the new version of the app. Please let me know if you see this again in the next week or so, otherwise I'll close this issue next weekend.
