### ISSUE TITLE
Options menu is a bit quirky and perhaps too long

### ISSUE THREAD

**Issue by lukewatts** [jedfoster/SassMeister#168]
Firstly, I think the new layout is a great improvement overall!

However, the **Options** menu is a bit too long I feel. I think things could be grouped together more logically if they were broken out into 3 - 4 more top level menus.

The extensions menu definitely could do with being on it's own. It's actually popping out when I hover on **CSS Output** (see attached image)._ Browser latest Firefox (2016-03-04). Win 8.1_

![sassmeister-dropdown-issue](https://cloud.githubusercontent.com/assets/4622166/13529810/fe3a944e-e215-11e5-85f6-eb7c18575f91.jpg)

Perhaps something like would be simpler: 
- Sass
  - Compilers
  - Syntax
- CSS/HTML
  - CSS Output
  - HTML Syntax
  - Autoprefixer
- Extension
- Options (or Settings or Preferences)
  -Theme
  - Emmet Key Bindings
  - Vim Key Bindings
  - Scroll Past End
  - Browsers...

_OR_
- Compilers
  - Sass Compiler (Ruby, Libsass...)
  - Sass Syntax (SCSS/Sass)
  - HTML Compiler (Jade, Slim, HAML...)
- Output
  - CSS Output
  - Autoprefixer
- Extension
- Options (or Settings or Preferences)
  -Theme
  - Emmet Key Bindings
  - Vim Key Bindings
  - Scroll Past End
  - Browsers...

Just suggestions of course :)

**Comment by jedfoster** [comment]
Interesting...

**Comment by indrekpaas** [comment]
On the same note for a better UX: [Dropdown Menus with More Forgiving Mouse Movement Paths](https://css-tricks.com/dropdown-menus-with-more-forgiving-mouse-movement-paths/)
