### ISSUE TITLE
Can't save Gist when including HTML

### ISSUE THREAD

**Issue by Nooshu** [jedfoster/SassMeister#169]
Hello,

I seem to be having trouble saving a Gist when anything is included in the HTML tag. For example when I include this:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Media Query</title>
  </head>
  <body>
  <ul class="list">
    <li>List 1</li>
    <li>List 2</li>
  </ul>
  </body>
</html>
```

I get a response saying `POST https://api.github.com/gists 422 (Unprocessable Entity)`:

```
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "Gist",
      "code": "missing_field",
      "field": "files"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/gists/#edit-a-gist"
}
```

The Scss and CSS save fine in the Gist, just not when any HTML is present. I've tried clearing cookies, revoking Github access and re-adding, and also tried a different browser. I'm a little stumped as to what is causing it.

Any ideas?

Thanks!

**Comment by jedfoster** [comment]
Should be fixed now. Thanks for reporting the problem!
