### ISSUE TITLE
Firefox won't copy text from the output textarea.

### ISSUE THREAD

**Issue by PauloFrancaLacerda** [jedfoster/SassMeister#170]
I can't get Firefox to copy the output text - it looks like a bug in the browser.
Today I tried with Firefox v43, v44, v45 (latest stable version) and even v46 (beta). Still buggy.

I've been facing the same problem when using other source-transformation sites (only with Firefox), such as code formatters and minifiers. Chrome does copy perfectly from all of them.

Sugestion:
In order to avoid the issue, SassMeister could offer a [save to file] and a [copy to clipboard] buttons. This would actually "save" users from the hell of having to use another browser just to do a simple copy-and-paste task.

In time:
Also tried loading Firefox in Safe Mode (all addons disabled).
Same problem. :(

Thanks in advance.

**Comment by jedfoster** [comment]
I am not able to replicate this issue—I can copy from the result pane just fine.

**Comment by PauloFrancaLacerda** [comment]
Just tested it again with FireFox v47.0-b4 (on Windows 7, x86).
After tried to copy the results, all I got by pasting the output text is this Unicode character: 
