### ISSUE TITLE
Not recompiling after switching engine

### ISSUE THREAD

**Issue by mgreter** [jedfoster/SassMeister#172]
When switching the compiler, the input is not recompiled until a change is made to the input.
I would argue that it makes sense to update the result when switching engines immediately.

**Comment by stowball** [comment]
Thanks for logging this @mgreter, because, yep, it definitely tripped me up!

**Comment by stowball** [comment]
Love your work, @jedfoster

**Comment by xzyfer** [comment]
\o/
