### ISSUE TITLE
New extension: sass-mediaqueries

### ISSUE THREAD

**Issue by rafalbromirski** [jedfoster/SassMeister#175]
#### What's that?

> It's a collection of useful Media Queries mixins for Sass (including iOS devices, TVs and more). Fully customizable and very easy to use.

Repo: https://github.com/paranoida/sass-mediaqueries
Website: http://paranoida.github.com/sass-mediaqueries
Demo: https://paranoida.github.io/sass-mediaqueries/demo.html

Works with ruby-sass & libsass.

Let me know if I can speed it up.

Cheers.

**Comment by jedfoster** [comment]
Added
