### ISSUE TITLE
Can't Scroll With Scrollbar

### ISSUE THREAD

**Issue by stowball** [jedfoster/SassMeister#176]
On Mac at least, people like myself who don't have trackpads or mouse wheels need to grab the scrollbar to scroll, but it's impossible to do so as the pane resizing takes over :(

See the GIF
![cant-scroll-sassmeister](https://cloud.githubusercontent.com/assets/853552/15764432/3aebdd7c-296e-11e6-8f5f-baf1768b137b.gif)

**Comment by xzyfer** [comment]
Scrolling is also broken on mobile.
