### ISSUE TITLE
Improve legibility by disabling font smoothing

### ISSUE THREAD

**Issue by indrekpaas** [jedfoster/SassMeister#177]
I use this app daily, but never got around bringing the following issue to authors' attention: 

Legibility can be greatly improved by disabling font smoothing. The benefit is especially prominent on non-retina screens. [Please Stop "Fixing" Font Smoothing](http://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/) is a great article on the topic, explaining why this feature is better left untouched.

![SassMeister](http://i.imgur.com/pzwUSOT.png)

**Comment by jedfoster** [comment]
What platform are you on? 

I have to say I strongly disagree; on every platform I've reviewed Sassmeister (including my retina MacBook Pro—at any resolution—and my cheap 1680x1050 22" LCD) non-antialiased text looks hideous.

**Comment by indrekpaas** [comment]
The screenshot is taken with retina iMac on OS X 10.11. I do experience the same issue on MacBook Air, Thunderbolt Display and on a cheap 2560x1600 LCD screen.

Can you post your on/off screenshot for comparison? I'm really curious to see your experience.
