### ISSUE TITLE
Indent settings

### ISSUE THREAD

**Issue by CupOfTea696** [jedfoster/SassMeister#178]
It'd be nice to be able to configure indent settings. Currently, indentation is set to two spaces, but I always use 4 in my projects. Copy and pasting code between sassmeister and my code editor gets annoying since it produces mixed indentation.

**Comment by jedfoster** [comment]
Personally, I think anything other than 2 spaces is _craaaazy_—but hey, different strokes... At least you're not asking for emacs keybindings. 😀

**Comment by CupOfTea696** [comment]
Well I write a lot in PHP, and the [PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md) standard specifies 4 spaces, so that's what my editor is configured to :p
