### ISSUE TITLE
SassMeister saves gone, Not showing any output, Gists are still present

### ISSUE THREAD

**Issue by monolux** [jedfoster/SassMeister#187]
In this [issue](https://github.com/oddbird/susy/issues/628) I have shared a couple of SassMeister gists about Susy, the last one a couple of hours old, did bookmark them and @mirisuzanne could see them, now they are all gone.

Also gists I made that are older are all gone.

http://www.sassmeister.com/gist/d03575a967842b9452eaa54ae96192e1

http://www.sassmeister.com/gist/7f22e44ace49b5124eec

http://www.sassmeister.com/gist/eab5ee589a011816b1be868230a6fb7b

http://www.sassmeister.com/gist/4e412a533c5b7d978e887df9797093be

http://www.sassmeister.com/gist/a77da1f77143f2fac4bd11e428206b96

http://www.sassmeister.com/gist/d03575a967842b9452eaa54ae96192e1

Would be great to get those back if possible, they are all listed under Gist in my GitHub account, however on SassMeister they redirect to the index page.

Is this something to do with my account settings on GitHub or Gist?
Though I never changed anything there.

Thank you for any help.

**Comment by monolux** [comment]
Now SassMeister is not showing any output.

https://www.sassmeister.com/gist/223c6bbf97031c4ab5d47e66344280a4

Tried with latest FF and Chrome for desktop.
Am I doing something wrong?

**Comment by jedfoster** [comment]
I think this is fixed now. I've verified that the links referenced in #188  and oddbird/susy#628 all work now.

**Comment by monolux** [comment]
Thank you man!
