### ISSUE TITLE
Sass Gists Gone

### ISSUE THREAD

**Issue by monolux** [jedfoster/SassMeister#188]
Indrek Paas' [Sass mixin](http://sassmeister.com/gist/7f22e44ace49b5124eec) [for fluid type ](https://madebymike.com.au/writing/fluid-type-calc-examples/) is gone.

The link to the gist on Sassmeister redirects to the index page, every time, in any browser, desktop and mobile, on private and open networks.

So now not only my own gists but also other people's gists start disappearing.
Can you look into this please?

**Comment by jedfoster** [comment]
I'll take a look at this. I suspect the recent HTTPS feature of the app may be incorrectly redirecting this URL.

**Comment by monolux** [comment]
Before I could hit send on an email I was just writing to you you got back, thanks you heaps!

**Comment by jedfoster** [comment]
I think this is fixed now. I've verified that the links referenced in #187 and oddbird/susy/issues/628 all work now.

**Comment by monolux** [comment]
Excellent, thank you heaps for your efforts Jed!
