### ISSUE TITLE
C++ -style commnents miss closing tag on conversion

### ISSUE THREAD

**Issue by nocke** [jedfoster/SassMeister#190]
Wonderful tool your wrote :+1: 
Although the thing I use, the option to convert **scss←→sass** is a little bit hidden (by switching under options between the two. Or is there another way? I would be curious, what you use for this type of conversion, btw.)

Either way: Minor mistake on that conversion: Closing `*/` on „C-style“ comments is missing:

![selection_206](https://user-images.githubusercontent.com/21154106/32946137-93f4cb56-cb96-11e7-9c3b-8912787ffa97.png)

**Comment by jedfoster** [comment]
Thanks for the compliments.

The app uses Sass's built in conversion tool, [`sass-convert`](http://sass-lang.com/documentation/#sass-convert).

The closing `*/` for C-style comments is stripped out by the converter and is actually incompatible with the indented Sass syntax. Read more about [indented syntax comments.](http://sass-lang.com/documentation/file.INDENTED_SYNTAX.html#Comments)
