### ISSUE TITLE
Update Sass versions

### ISSUE THREAD

**Issue by nex3** [jedfoster/SassMeister#191]
The Sass versions on SassMeister are currently fairly out-of-date. This is causing confusion for users—see for example sass/sass#2415. It would be great to update to the latest versions of all the implementations:

* [x] libsass 3.5.0.beta.3
* [x] Ruby Sass 3.5.3
* [x] Ruby Sass 3.4.25

**Comment by jedfoster** [comment]
Aahhhh. My apologies, I'm just now seeing this issue.

I have not been able to give SassMeister the attention it deserves in the last year, but I expect to have time next week. I will absolutely update all the things.

**Comment by xzyfer** [comment]
Is there something I can do help keep things updated?

**Comment by jedfoster** [comment]
@xzyfer I don't know. Do you know a cure for burnout? Aside from the janky architecture of the app itself, burnout the been the biggest reason things aren't up to date.

**Comment by xzyfer** [comment]
Sorry to hear that mate. 

Is there a way I can prep PRs for updates or is it all behind the scenes somewhere?

**Comment by jedfoster** [comment]
I've updated Ruby Sass 3.5 and 3.4, and LibSass to the latest versions of each. 

Looks like Ruby Sass 4.0 is dead at `4.0.0.alpha.1`? No more recent versions? Should I keep it available on the app?

**Comment by xzyfer** [comment]
The current Ruby Sass 4 is pretty far behind last I checked. I suggest
removing it for now, there's not likely to be a stable Ruby Sass 4.

**Comment by jedfoster** [comment]
Will do. Thanks @xzyfer.

Closing this issue.
