### ISSUE TITLE
Add Dart Sass support

### ISSUE THREAD

**Issue by nex3** [jedfoster/SassMeister#192]
Dart Sass is going to be the reference implementation of Sass moving forward, and so should probably be supported by SassMeister. Let me know if you need any help getting it up and running.

**Comment by jedfoster** [comment]
Again, apologies, just now seeing this.

I will do what I can to spin up a Dart compiler. I know _nothing_ about Dart, so I expect a learning curve. Fortunately, I am about to be unemployed and should have some extra free time on my hands. So yay! (??)

**Comment by xzyfer** [comment]
The easiest way may be to use the node package? npm install dart-sass. It should have the same API as node-sass.

**Comment by jedfoster** [comment]
Oooohhh. Very good to know. That should make things much easier.

I assume that the Sass team would prefer Dart Sass be the default flavor on SassMeister? (The default is currently LibSass.)

**Comment by nex3** [comment]
> I assume that the Sass team would prefer Dart Sass be the default flavor on SassMeister? (The default is currently LibSass.)

Yeah, it's generally going to be at the front of the curve in terms of feature work.

**Comment by jedfoster** [comment]
@nex3 I ran into [dart-sass/issues/284](https://github.com/sass/dart-sass/issues/284). In lieu of [dart-sass/pull/303](https://github.com/sass/dart-sass/pull/303), I've patched my code to make import paths absolute within the app.

I'll have Dart Sass live on the app shortly.
