### ISSUE TITLE
Login via github gives me "Internal Server Error"

### ISSUE THREAD

**Issue by escapedcat** [jedfoster/SassMeister#195]
I clicked login, authorized github and after that I only get this:
![image](https://user-images.githubusercontent.com/1016218/39041631-b3fcb1ea-44bb-11e8-9483-bffa2669ee24.png)

**Comment by jedfoster** [comment]
Blargh. Thanks for the report.

I think I've fixed this; it's working for me now. Let me know if you still see issues.
