### ISSUE TITLE
Creating a new gist is a little confusing

### ISSUE THREAD

**Issue by csilverman** [jedfoster/SassMeister#199]
Would it be possible to put a "New" menu item under "File"? I'm new to SassMeister, and I had an issue this evening where I wasn't sure how to save a new gist without overwriting the previous one. I finally logged out and logged in again to reset it—I'm guessing this is a dumb thing to do, but I wasn't sure how else to reassure myself that it wasn't going to overwrite previous gists.

"New" is a pretty standard command for file menus, so I think having it would be a little more intuitive than Reset (which I initally tried, but it didn't clear the previous code).

 - Chris

**Comment by jedfoster** [comment]
So you've saved a gist and you're now at sassmeister.com/gist/xyz, and you want to start over and create a new gist, is that correct?

**Comment by csilverman** [comment]
Yes, exactly.
