### ISSUE TITLE
%placeholder works only in sassy syntax, not in sass

### ISSUE THREAD

**Issue by wilmaed** [jedfoster/SassMeister#201]
```
%foo
  color:black
b
  @extend %foo
  font-size: 12px 
```

------------
"b" failed to @extend "%foo".
Why?

No error in sassy syntax:

--------
```
%foo {
  color:black
}

b {
  @extend %foo;
  font-size: 12px;
}
```

**Comment by jedfoster** [comment]
Works with SCSS syntax: https://www.sassmeister.com/gist/f8e62964da4e1898d2108c31cbff20bd
Works with Sass syntax: https://www.sassmeister.com/gist/07af5909ad0f62e7d850caba54f768fc

**Comment by wilmaed** [comment]
Works not with sass syntax:
![screen1](https://user-images.githubusercontent.com/31799538/40928945-599f206c-6823-11e8-982d-afef940cac85.png)

Works not with sass syntax:
![screen2](https://user-images.githubusercontent.com/31799538/40928947-59c8cb60-6823-11e8-85a1-fda334a66380.png)

**Comment by wilmaed** [comment]
my sample works only with your url
Works with Sass syntax: https://www.sassmeister.com/gist/07af5909ad0f62e7d850caba54f768fc

not with www.sassmeister.com

**Comment by jedfoster** [comment]
Do me a favor and add a space before `black` on line 2. 

```sass
%foo
  color: black
```

I'm pretty sure the Sass syntax _requires_ a space after colons in property declarations; and a missing space would cause that placeholder class to be invalid, and thus "not found."

If that doesn't fix it, please report this issue to the Sass organization, https://github.com/sass/sass/issues

**Comment by wilmaed** [comment]
Yes, this will fix it. 

This is strange, because it works without space with 2 online compiler:

It's working on beautifytools.com:

![screen3](https://user-images.githubusercontent.com/31799538/40931862-e66de83a-682c-11e8-8449-3704627241b3.png)


and here on sass.js:
![screen4](https://user-images.githubusercontent.com/31799538/40931871-ed274c20-682c-11e8-90c1-d25ab096c6be.png)

**Comment by jedfoster** [comment]
`¯\_(ツ)_/¯`

Both of those tools use a hacky implementation of Sass that's transpiled into JavaScript and runs in the browser. SassMeister.com uses the real Sass binaries and runs server-side, rendering exactly the same output you would get if you compiled locally. Can't say the same for the Emscripten ports.
