### ISSUE TITLE
Characters disapear, output broken

### ISSUE THREAD

**Issue by kartofelek007** [jedfoster/SassMeister#210]
Was there any update?
Now there is some bugs:
- when i change output style - nothing happend
- when i write code, somethimes characters disapears, somethimes lines disapear etc.

![poprawiony](https://user-images.githubusercontent.com/2007669/93176857-305c4400-f732-11ea-8002-3c034c90ed1c.gif)

**Comment by jedfoster** [comment]
Thanks for this. Yes, I recently rewrote the entire app (the source code for which lives in a different, private repo, for now.) 

Not sure what's going on here, but looks like there might be something going on with the Ace editor. I'll look into it.

**Comment by jedfoster** [comment]
I've increased the debounce period to 750ms (up from 500). That seems to mitigate the issue, but does not solve it. 750ms is what I was using in the old app.

**Comment by aravinth-r-7867** [comment]
@jedfoster  Please fix this quickly. Sassmeister is always been very helpful for writing Sass code and check whether it is compiling to expected CSS or not. I'm really happy with the old version itself. Is there anyway to use the old version???

**Comment by jedfoster** [comment]
Ok. Took another pass at it and I think I have this issue fixed now. 

@kartofelek007 and @AravinthAro please refresh the app (clear your cache, too) and let me know if things are better now. 

I'll leave this issue open for a few days.

**Comment by chriskirknielsen** [comment]
Just had a play around and it seems to be working pretty smoothly on my end. Thank you @jedfoster!

**Comment by kartofelek007** [comment]
If I use expanded or compressed style - css is generated. But if I use nested, compact - css is not generated.

**Comment by jedfoster** [comment]
@kartofelek007 would you please open a new issue for that? And please include a gist that shows that issue.

**Comment by kartofelek007** [comment]
https://github.com/jedfoster/SassMeister/issues/211
