### ISSUE TITLE
Receive Page 404 Error and can't leave

### ISSUE THREAD

**Issue by TylerAPfledderer** [jedfoster/SassMeister#213]
Hello!

I'm receiving the "Gist: 404" page error, and I am not able to leave it. The "new gist" link produces ```undefined``` object literal through ```react_devtools_backend.js``` line 2450 in Chrome dev tools. 

Clearing browser cache and cookies does not resolve this.

In short, I can't use SASSMeister!

Thank you.

**Comment by jedfoster** [comment]
- Can you post your URL? 
- Are you signed in to GitHub? 
- Does the "File > Reset" control have any effect?

**Comment by TylerAPfledderer** [comment]
- The 404 is just at the url https://www.sassmeister.com/ with no extension
- I do not know if I still am since I have cleared browser cache, cookies, passwords, etc. I do not have authorization currently set in my GitHub settings.
- The "file" option does not exist

This is all I see:
![image](https://user-images.githubusercontent.com/65234762/97501493-baa9e180-1947-11eb-84db-21649ecbc0ef.png)
