### ISSUE TITLE
Changing the selected compiler should recompile the input automatically

### ISSUE THREAD

**Issue by stof** [jedfoster/SassMeister#215]
Currently, when I select a different compiler, the input does not get recompiled until I change it again. This makes it painful to test the same input in dart-sass and libsass for instance.

**Comment by jedfoster** [comment]
Do you have a sample gist that would show different output with different compilers?

**Comment by stof** [comment]
Not as a saved gist, but I have an example in https://github.com/sass/sass/issues/2931
