### ISSUE TITLE
sharing a gist-based URL does not populate the SCSS tab

### ISSUE THREAD

**Issue by stof** [jedfoster/SassMeister#216]
Open the link https://www.sassmeister.com/gist/c5ba452d2056365634d6b216f3fe7876

The output panel is properly showing the rendered output. But the scss panel is empty, which makes the sharing a lot less useful.

**Comment by jedfoster** [comment]
Forked the gist for posterity: https://gist.github.com/jedfoster/1a6744de0cf047abafc6bea4300f7ee7

**Comment by stof** [comment]
This seems to be working now. It loads the left panel (or maybe there's a race condition somewhere and I'm now lucky, if you haven't changed it yet)

**Comment by patocallaghan** [comment]
I'm also seeing this behaviour. The left hand panel isn't being populated with the SCSS and appears empty.

@jedfoster even using your forked gist I see this behaviour: https://www.sassmeister.com/gist/1a6744de0cf047abafc6bea4300f7ee7

![image](https://user-images.githubusercontent.com/685034/105734709-d44ccc00-5f2a-11eb-9d96-13a372d97db5.png)

I'm on MacOS Big Sur but this is consistent across latest Chrome, Edge, Firefox and Safari.
