### ISSUE TITLE
Editor lost focus

### ISSUE THREAD

**Issue by kartofelek007** [jedfoster/SassMeister#218]
When you stop type code, after 0.5s cursor disapear, active line jump to last line, and editor **lost focus**. 
This is very annoing, because when you want delete letter, you press backspace and go to previous page.

![n3ICx3nyku](https://user-images.githubusercontent.com/2007669/118302024-04bd7380-b4e4-11eb-91d2-865b78c8a31d.gif)

**Comment by scheibome** [comment]
The problem should be fixed. At least for me everything runs as usual again.

https://twitter.com/sassmeisterapp/status/1394392491751739393

**Comment by jedfoster** [comment]
Pushed a fix yesterday. Received several reports that this is resolved.
