### ISSUE TITLE
`sassmeister.com` is down

### ISSUE THREAD

**Issue by strarsis** [jedfoster/SassMeister#219]
The site is down (`DNS_PROBE_FINISHED_NXDOMAIN`).

**Comment by joakim-roos** [comment]
yeah, was about to share some stuff with a colleague. @jedfoster is it only temporary?

**Comment by jasonteunissen** [comment]
my fav tool is down :|

**Comment by strarsis** [comment]
@joakim-roos, @jasonteunissen: 
It works again (probably for some days now)! 👍
