### ISSUE TITLE
Suggestions for potential "pro" features

### ISSUE THREAD

**Issue by lunelson** [jedfoster/SassMeister#63]
I tweeted to `@sassmeister` today that I'd pay for pro features if they built them. This is a follow-up to outline what I had in mind. Basically: features which might require a development investment—and possibly ongoing overhead—such that they would require a subscription.

1. **gist importing, as with libraries**. This was my main thought: I do a lot of debugging in sassmeister and have to paste in sometimes hundreds of lines of library code first before I can debug the stuff I'm after. It would be great if I could keep that stuff in separate gists and just pull it in. I imagine a syntax similar to the way we can already include libraries: e.g. `@import "gist/654321";`
4. **ability to name gists, and acess and retrieve them by name**. One of the downsides with gists and sassmeister is that I have many many gists now that are all called "Sassmeister Input", when I view them on github. But conceivably, sassmeister could keep track of gists that I create through the SM interface, and potentially also store a name for each one (perhaps in a banner block comment), such that from within SM I could see my sm gists by name.
2. **custom banner**. This is a kind of corrollary to the two points above: if I could set a preference on sassmeister to always start a new file—such as you get when you hit 'reset'—with a custom banner, I could set some defaults for the naming, description and also custom `@import` statements on my files. Something like a boilerplate I guess.
3. **user-selectable version of sass (i.e. ruby vs. libsass)**. Due to the growing interest in libsass, it would be great to actually work with that compiler. I'm migrating some code from ruby 3.3.x to libsass and in order to emulate what that version can support I have to use a local clone of the sassmeister sandbox, checked out at a pre-3.3 state (this being the closest replication of the current state of libsass' functionality). I don't have this hooked up with github access or anything so I don't get any of that other functionality, making it a bit less convenient (though a local sassmeister is faster ;)). Would be great if one could switch versions/compilers on the fly.

**Comment by jedfoster** [comment]
I would _LOVE_ to have all these features, but the work to build even just the foundation of a "pro" version of SassMeister is simply too great. 

After several months working on a service to handle user accounts (essential for being able to charge for additional features) I've come to the conclusion that SassMeister Pro just isn't feasible on my own. At least not in the foreseeable future.

**Comment by lunelson** [comment]
Totally understood, thanks for all your work @jedfoster
