### ISSUE TITLE
@import other sassmeister gists

### ISSUE THREAD

**Issue by xzyfer** [jedfoster/SassMeister#72]
More broadly it'd rad to include external resources. This would enable simulating things like filesystem or dependant libraries that aren't part of SassMeister.

JSFiddle enable this via their "External Resources" setting.

I think preprocessing (hijacking) `@import` would be an elegant way to deal with import SassMeister gists.

```
@import "gist/8595756"; // wget the gist and do some load path magic
```

**Comment by jedfoster** [comment]
I doubt this will ever happen. https://github.com/jedfoster/SassMeister/issues/63#issuecomment-72350041
