### ISSUE TITLE
Is it possible to get see Sass `@warn`s?

### ISSUE THREAD

**Issue by matthew-andrews** [jedfoster/SassMeister#73]
https://twitter.com/andrewsmatt/status/426311646936444928
> Is there any way to get sassmeister to output `@warn`s?
E.g. http://sassmeister.com/gist/8564033

**Comment by dariuszsikorski** [comment]
Up, still can't @debug. It's really important, for example when writing a sass function, the only way to check values inside is to use @debug or @warn. For @mixin s this can be solved with  ... { debug: "message"; }

**Comment by jedfoster** [comment]
See #144. This is still blocked.
